// const multer = require("multer");
// const path = require("path");
// const shortId = require("shortid");
// const Image = require("../models/Image");

// // const storage = multer.diskStorage({
// //   destination: function (req, file, cb) {
// //     const uploadDir = path.resolve(__dirname, "../public/uploads/weblog"); // Resolve the path relative to the current script file
// //     cb(null, uploadDir);
// //   },
// //   filename: function (req, file, cb) {
// //     const fileExt = path.extname(file.originalname); // Get the file extension
// //     const baseName = path.basename(file.originalname, fileExt); // Get the filename without the extension
// //     const uniqueName = baseName + "-" + shortId() + fileExt; // Combine filename + shortId + filetype
// //     cb(null, uniqueName);
// //   },
// // });

// // const upload = multer({
// //   storage: storage,
// // }).single("upload");
// // !vercel
// const storage = multer.diskStorage({
//   destination: function (req, file, cb) {
//     cb(null, "/tmp"); // فقط روی Vercel قابل نوشتن
//   },
//   filename: function (req, file, cb) {
//     const fileExt = path.extname(file.originalname);
//     const baseName = path.basename(file.originalname, fileExt);
//     const uniqueName = baseName + "-" + shortId() + fileExt;
//     cb(null, uniqueName);
//   },
// });

// const upload = multer({ storage }).single("upload");


// exports.UploadWeblogImage = async (req, res) => {
//   upload(req, res, async function (err) {
//     if (err instanceof multer.MulterError) {
//       // A Multer error occurred when uploading.
//       console.log(err);
//       return res.status(400).json({ error: "File upload error" });
//     } else if (err) {
//       // An unknown error occurred when uploading.
//       console.log(err);
//       return res.status(500).json({ error: "Internal server error" });
//     }
//     // Everything went fine.
//     // You can now use req.file to access information about the uploaded file.
//     // For example, req.file.filename gives the unique filename generated by multer.
//     const imageName = req.file.filename;
//     try {
//       await Image.create({
//         imageName,
//         // direction: `http://localhost:5000/uploads/weblog/${imageName}`,
//         // direction: `https://abtin-kerman-backend-new.vercel.app/uploads/weblog/${imageName}`,
//         direction: `https://api.kermanatari.ir/uploads/weblog/${imageName}`,
//       });
//       return res.status(201).json({
//         uploaded: true,
//         //! change
//         url: `https://api.kermanatari.ir/uploads/weblog/${imageName}`,
//         // url: `http://localhost:5000/uploads/weblog/${imageName}`
//         // url: `https://abtin-kerman-backend-new.vercel.app/uploads/weblog/${imageName}`
//       });
//     } catch (err) {
//       console.log(err);
//       return res.status(500).json({ error: "Internal server error" });
//     }
//   });
// };

const multer = require("multer");
const path = require("path");
const shortId = require("shortid");
const Image = require("../models/Image");

// استفاده از memoryStorage به جای diskStorage
const storage = multer.memoryStorage();
const upload = multer({ storage }).single("upload");

exports.UploadWeblogImage = async (req, res) => {
  upload(req, res, async function (err) {
    if (err instanceof multer.MulterError) {
      console.log(err);
      return res.status(400).json({ error: "File upload error" });
    } else if (err) {
      console.log(err);
      return res.status(500).json({ error: "Internal server error" });
    }

    if (!req.file) {
      return res.status(400).json({ error: "No file uploaded" });
    }

    // تولید یه اسم یونیک تستی
    const fileExt = path.extname(req.file.originalname);
    const baseName = path.basename(req.file.originalname, fileExt);
    const imageName = `${baseName}-${shortId()}${fileExt}`;

    try {
      await Image.create({
        imageName,
        // این لینک واقعی نیست، فقط برای تست
        direction: `https://api.kermanatari.ir/uploads/weblog/${imageName}`,
      });

      return res.status(201).json({
        uploaded: true,
        url: `https://api.kermanatari.ir/uploads/weblog/${imageName}`, // لینک صرفاً تستی
      });
    } catch (err) {
      console.log(err);
      return res.status(500).json({ error: "Internal server error" });
    }
  });
};
